name: Notify Committer Re-useable workflow
# IMPORTANT NOTE:
#       this workflow either has to be in the same repository as the calling workflow OR
#       this workflow needs to reside in a public repository. Github doesn't now allow the
#       reuse of workflows residing in a private repository.
#       See also https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations
on:
  workflow_call:
    inputs:
      failure:
        required: true
        type: boolean
    secrets:
      SLACK_BOT_TOKEN:
        required: true
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Resolve slack committer
        id: slack-committer
        uses: penchef/slack-committer@v1.2
        with:
          fallback: "XYZXYZXYZ"
          user-mapping: >
            {
              "Penchef": "UUSAQBVDZ",
            }
      - name: Notify user
        # choose whatever notify action suits you, using voxmedia/github-action-slack-notify-build as an example
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: ${{ inputs.failure }}
        uses: voxmedia/github-action-slack-notify-build@v1.6.0
        with:
          channel_id: ${{ steps.slack-committer.outputs.username }}
          status: FAILED
          color: danger
